sudo: required
language: cpp

git:
  depth: 1

cache:
  directories:
  - deps/boost

stages:
- lint
- test
- deploy

jobs:
  include:
  - os: osx
    stage: lint
    compiler: clang++
    script: (! cmake --build "${BUILD_PATH}" --target doc 2>&1 | grep --color -iE "warning|error")

  - os: linux
    stage: lint
    script: (! cmake --build "${BUILD_PATH}" --target doc 2>&1 | grep --color -iE "warning|error")

  - os: linux
    stage: lint
    compiler: clang++
    script: (cd "${BUILD_PATH}" && ctest --output-on-failure -R ^test.format)

  - os: osx
    stage: test
    compiler: clang++

  - os: linux
    dist: xenial
    stage: test
    compiler: g++
    env: VERSION=4.7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cppcheck
          - g++-4.7

  - os: linux
    stage: test
    compiler: g++
    addons:
      apt:
        packages:
          - cppcheck

  - os: linux
    dist: trusty
    stage: test
    compiler: clang++
    env: VERSION=3.4 CXXFLAGS="-stdlib=libc++"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.4 main'
            key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
          - clang-3.4
          - libc++-dev
          - libc++abi-dev

  - os: linux
    stage: test
    compiler: clang++

  - os: linux
    stage: deploy
    script:
    - cmake --build "${BUILD_PATH}" --target doc
    - cmake --build "${BUILD_PATH}" --target install
    - tree "${INSTALL_PATH}"
    addons:
      apt:
        packages:
        - tree
    deploy:
    - provider: pages
      target-branch: standalone
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      keep-history: true
      allow-empty-commit: true
      local-dir: install/include
      on:
        tags: true

    - provider: pages
      target-branch: gh-pages
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      keep-history: true
      allow-empty-commit: true
      local-dir: install/share/Metal/doc
      on:
        tags: true

before_install:
- SOURCE_PATH="${TRAVIS_BUILD_DIR}"

- BUILD_PATH="${TRAVIS_BUILD_DIR}/build/"
- mkdir -p "${BUILD_PATH}"

- INSTALL_PATH="${TRAVIS_BUILD_DIR}/install/"
- mkdir -p "${INSTALL_PATH}"

- DEPS_PATH="${TRAVIS_BUILD_DIR}/deps/"
- mkdir -p "${DEPS_PATH}"

- |
  if [[ -n "${VERSION}" ]]
  then
    export CC="${CC}-${VERSION}"
    export CXX="${CXX}-${VERSION}"
  fi

install:
# Doxygen
- |
  if [[ "${TRAVIS_BUILD_STAGE_NAME}" != "Test" ]]
  then
    DOXYGEN_URL="http://doxygen.nl/files/doxygen-1.8.16.linux.bin.tar.gz"
    mkdir -p "${DEPS_PATH}/doxygen"
    travis_retry curl -L "${DOXYGEN_URL}" | tar --strip-components=1 -xz -C "${DEPS_PATH}/doxygen" || exit $?
    export PATH="${DEPS_PATH}/doxygen/bin:${PATH}"
  fi

# Boost
- |
  if [[ -d "${DEPS_PATH}/boost/.git" ]]
  then
    git -C "${DEPS_PATH}/boost" submodule update --recursive || exit $?
  else
    BOOST_URL="https://github.com/boostorg/boost.git"
    travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} "${DEPS_PATH}/boost" || exit $?
  fi

- (cd "${DEPS_PATH}/boost" && ./bootstrap.sh && ./b2 headers)

before_script:
- CMAKE_ARGS+=("-H${SOURCE_PATH}")
- CMAKE_ARGS+=("-B${BUILD_PATH}")
- CMAKE_ARGS+=("-DCMAKE_INSTALL_PREFIX=${INSTALL_PATH}")
- CMAKE_ARGS+=("-DBOOST_ROOT=${DEPS_PATH}/boost")
- cmake ${CMAKE_ARGS[@]}

script:
- (cd "${BUILD_PATH}" && ctest --output-on-failure -E ^test.format)

notifications:
  webhooks:
  urls: https://webhooks.gitter.im/e/f0433b6f1de0942ea9a8
  on_success: change
  on_failure: always
