# Copyright Bruno Dutra 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

clone_depth: 1
platform: x64

matrix:
    fast_finish: false

environment:
    matrix:
      - GENERATOR: Visual Studio 14 2015
      - GENERATOR: Visual Studio 14 2015 Win64

before_build:
  - mkdir "%APPVEYOR_BUILD_FOLDER%\build"
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - cmake -G"%GENERATOR%" "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - cmake --build "%APPVEYOR_BUILD_FOLDER%\build" --target examples
  - cmake --build "%APPVEYOR_BUILD_FOLDER%\build" --target tests

test_script:
  - ctest
