# Copyright Bruno Dutra 2015-2016
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

clone_depth: 1
platform: x64

matrix:
    fast_finish: false

environment:
    matrix:
      - GENERATOR: Visual Studio 14 2015
      - GENERATOR: Visual Studio 14 2015 Win64

install:
  - choco install doxygen.portable

before_build:
  - set "METAL_SOURCE_PATH=%APPVEYOR_BUILD_FOLDER%"
  - set "EXTERNAL_SOURCE_PATH=%METAL_SOURCE_PATH%\example\external"

  - set "METAL_BUILD_PATH=%APPVEYOR_BUILD_FOLDER%\build"
  - mkdir "%METAL_BUILD_PATH%"

  - set "METAL_INSTALL_PATH=%APPVEYOR_BUILD_FOLDER%\install"
  - mkdir "%METAL_INSTALL_PATH%"

  - set "EXTERNAL_BUILD_PATH=%METAL_BUILD_PATH%/example/external"
  - mkdir "%EXTERNAL_BUILD_PATH%"


  - pushd "%METAL_BUILD_PATH%" && cmake -G"%GENERATOR%" "%METAL_SOURCE_PATH%" -DCMAKE_INSTALL_PREFIX="%METAL_INSTALL_PATH%" & popd
  - cmake --build "%METAL_BUILD_PATH%" --target install

  - pushd "%EXTERNAL_BUILD_PATH%" && cmake -G"%GENERATOR%" "%EXTERNAL_SOURCE_PATH%" -DCMAKE_PREFIX_PATH="%METAL_INSTALL_PATH%" & popd

build_script:
  - cmake --build "%EXTERNAL_BUILD_PATH%" --target external
  - cmake --build "%METAL_BUILD_PATH%" --target doc
  - pushd "%METAL_BUILD_PATH%" && ctest --output-on-failure & popd
